name: App Testing

on: [push]

jobs:
  android:
    name: Android Testing
    runs-on: ubuntu-latest
    env:
      AWS_DEVICEFARM_PROJECT_ARN: arn:aws:devicefarm:us-west-2:504319505922:project:8ca7b4f6-ac5c-414a-a0d1-5ec9e9c7be09

    steps:
      - name: Configure AWS Credentials For Github Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          mask-aws-account-id: true
      - name: Create upload link for apk
        id: create_upload
        run: echo "response=$(aws devicefarm create-upload --project-arn $AWS_DEVICEFARM_PROJECT_ARN --name application.apk --type ANDROID_APP)" >> $GITHUB_OUTPUT
      - name: Upload apk file
        run: curl -T build/application.apk ${{fromJSON(steps.create_upload.outputs.response).upload.url}}

